---
apiVersion: v1
kind: Service #type 
metadata: #Configuration des metadata
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic-dev
spec:
  ports: # Exposition des port d'entré et de sortie
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer #Un service de type LoadBalancer est basé sur le service NodePort et ajoute la possibilité de configurer des équilibreurs de charge externes au sein des clouds publics et privés. Il expose les services exécutés au sein du cluster en transférant le trafic réseau vers les nœuds du cluster.
status:
  loadBalancer: {}